/* The following code was generated by JFlex 1.4.3 on 26.02.16 18:59 */

package com.octaveide.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import static com.octaveide.psi.OctaveTypes.*;
import com.intellij.psi.TokenType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 26.02.16 18:59 from the specification file
 * <tt>D:/dev/IdeaPlugin/octave-idea-plugin/src/com/octaveide/lexer/_OctaveLexer.flex</tt>
 */
public class _OctaveLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\33\1\0"+
    "\1\4\1\11\1\4\1\27\1\30\1\13\1\14\1\21\1\17\1\0"+
    "\1\10\1\25\1\22\1\5\11\6\1\12\1\35\1\31\1\20\1\32"+
    "\2\0\4\11\1\7\25\11\1\0\1\23\1\0\1\24\1\11\1\0"+
    "\3\11\1\11\1\7\1\11\1\11\1\11\2\11\11\11\1\11\6\11"+
    "\1\15\1\26\1\16\1\34\43\0\4\11\4\0\1\11\12\0\1\11"+
    "\4\0\1\11\5\0\27\11\1\0\37\11\1\0\u01ca\11\4\0\14\11"+
    "\16\0\5\11\7\0\1\11\1\0\1\11\201\0\5\11\1\0\2\11"+
    "\2\0\4\11\10\0\1\11\1\0\3\11\1\0\1\11\1\0\24\11"+
    "\1\0\123\11\1\0\213\11\10\0\236\11\11\0\46\11\2\0\1\11"+
    "\7\0\47\11\7\0\1\11\100\0\33\11\5\0\3\11\30\0\1\11"+
    "\24\0\53\11\43\0\2\11\1\0\143\11\1\0\1\11\17\0\2\11"+
    "\7\0\2\11\12\0\3\11\2\0\1\11\20\0\1\11\1\0\36\11"+
    "\35\0\131\11\13\0\1\11\30\0\41\11\11\0\2\11\4\0\1\11"+
    "\5\0\26\11\4\0\1\11\11\0\1\11\3\0\1\11\27\0\31\11"+
    "\107\0\1\11\1\0\13\11\127\0\66\11\3\0\1\11\22\0\1\11"+
    "\7\0\12\11\17\0\7\11\1\0\7\11\5\0\10\11\2\0\2\11"+
    "\2\0\26\11\1\0\7\11\1\0\1\11\3\0\4\11\3\0\1\11"+
    "\20\0\1\11\15\0\2\11\1\0\3\11\16\0\4\11\7\0\1\11"+
    "\11\0\6\11\4\0\2\11\2\0\26\11\1\0\7\11\1\0\2\11"+
    "\1\0\2\11\1\0\2\11\37\0\4\11\1\0\1\11\23\0\3\11"+
    "\20\0\11\11\1\0\3\11\1\0\26\11\1\0\7\11\1\0\2\11"+
    "\1\0\5\11\3\0\1\11\22\0\1\11\17\0\2\11\17\0\1\11"+
    "\23\0\10\11\2\0\2\11\2\0\26\11\1\0\7\11\1\0\2\11"+
    "\1\0\5\11\3\0\1\11\36\0\2\11\1\0\3\11\17\0\1\11"+
    "\21\0\1\11\1\0\6\11\3\0\3\11\1\0\4\11\3\0\2\11"+
    "\1\0\1\11\1\0\2\11\3\0\2\11\3\0\3\11\3\0\14\11"+
    "\26\0\1\11\50\0\1\11\13\0\10\11\1\0\3\11\1\0\27\11"+
    "\1\0\12\11\1\0\5\11\3\0\1\11\32\0\2\11\6\0\2\11"+
    "\43\0\10\11\1\0\3\11\1\0\27\11\1\0\12\11\1\0\5\11"+
    "\3\0\1\11\40\0\1\11\1\0\2\11\17\0\2\11\22\0\10\11"+
    "\1\0\3\11\1\0\51\11\2\0\1\11\20\0\1\11\21\0\2\11"+
    "\30\0\6\11\5\0\22\11\3\0\30\11\1\0\11\11\1\0\1\11"+
    "\2\0\7\11\72\0\60\11\1\0\2\11\13\0\10\11\72\0\2\11"+
    "\1\0\1\11\2\0\2\11\1\0\1\11\2\0\1\11\6\0\4\11"+
    "\1\0\7\11\1\0\3\11\1\0\1\11\1\0\1\11\2\0\2\11"+
    "\1\0\4\11\1\0\2\11\11\0\1\11\2\0\5\11\1\0\1\11"+
    "\25\0\4\11\40\0\1\11\77\0\10\11\1\0\44\11\33\0\5\11"+
    "\163\0\53\11\24\0\1\11\20\0\6\11\4\0\4\11\3\0\1\11"+
    "\3\0\2\11\7\0\3\11\4\0\15\11\14\0\1\11\21\0\46\11"+
    "\1\0\1\11\5\0\1\11\2\0\53\11\1\0\u014d\11\1\0\4\11"+
    "\2\0\7\11\1\0\1\11\1\0\4\11\2\0\51\11\1\0\4\11"+
    "\2\0\41\11\1\0\4\11\2\0\7\11\1\0\1\11\1\0\4\11"+
    "\2\0\17\11\1\0\71\11\1\0\4\11\2\0\103\11\45\0\20\11"+
    "\20\0\125\11\14\0\u026c\11\2\0\21\11\1\0\32\11\5\0\113\11"+
    "\3\0\3\11\17\0\15\11\1\0\4\11\16\0\22\11\16\0\22\11"+
    "\16\0\15\11\1\0\3\11\17\0\64\11\43\0\1\11\3\0\2\11"+
    "\103\0\130\11\10\0\51\11\1\0\1\11\5\0\106\11\12\0\35\11"+
    "\63\0\36\11\2\0\5\11\13\0\54\11\25\0\7\11\70\0\27\11"+
    "\11\0\65\11\122\0\1\11\135\0\57\11\21\0\7\11\67\0\36\11"+
    "\15\0\2\11\12\0\54\11\32\0\44\11\51\0\3\11\12\0\44\11"+
    "\153\0\4\11\1\0\4\11\3\0\2\11\11\0\300\11\100\0\u0116\11"+
    "\2\0\6\11\2\0\46\11\2\0\6\11\2\0\10\11\1\0\1\11"+
    "\1\0\1\11\1\0\1\11\1\0\37\11\2\0\65\11\1\0\7\11"+
    "\1\0\1\11\3\0\3\11\1\0\7\11\3\0\4\11\2\0\6\11"+
    "\4\0\15\11\5\0\3\11\1\0\7\11\102\0\2\11\23\0\1\11"+
    "\34\0\1\11\15\0\1\11\20\0\15\11\3\0\33\11\107\0\1\11"+
    "\4\0\1\11\2\0\12\11\1\0\1\11\3\0\5\11\6\0\1\11"+
    "\1\0\1\11\1\0\1\11\1\0\4\11\1\0\13\11\2\0\4\11"+
    "\5\0\5\11\4\0\1\11\21\0\51\11\u0a77\0\57\11\1\0\57\11"+
    "\1\0\205\11\6\0\4\11\3\0\2\11\14\0\46\11\1\0\1\11"+
    "\5\0\1\11\2\0\70\11\7\0\1\11\20\0\27\11\11\0\7\11"+
    "\1\0\7\11\1\0\7\11\1\0\7\11\1\0\7\11\1\0\7\11"+
    "\1\0\7\11\1\0\7\11\120\0\1\11\u01d5\0\3\11\31\0\11\11"+
    "\7\0\5\11\2\0\5\11\4\0\126\11\6\0\3\11\1\0\132\11"+
    "\1\0\4\11\5\0\51\11\3\0\136\11\21\0\33\11\65\0\20\11"+
    "\u0200\0\u19b6\11\112\0\u51cd\11\63\0\u048d\11\103\0\56\11\2\0\u010d\11"+
    "\3\0\20\11\12\0\2\11\24\0\57\11\20\0\31\11\10\0\120\11"+
    "\47\0\11\11\2\0\147\11\2\0\4\11\1\0\4\11\14\0\13\11"+
    "\115\0\12\11\1\0\3\11\1\0\4\11\1\0\27\11\25\0\1\11"+
    "\7\0\64\11\16\0\62\11\76\0\6\11\3\0\1\11\16\0\34\11"+
    "\12\0\27\11\31\0\35\11\7\0\57\11\34\0\1\11\60\0\51\11"+
    "\27\0\3\11\1\0\10\11\24\0\27\11\3\0\1\11\5\0\60\11"+
    "\1\0\1\11\3\0\2\11\2\0\5\11\2\0\1\11\1\0\1\11"+
    "\30\0\3\11\2\0\13\11\7\0\3\11\14\0\6\11\2\0\6\11"+
    "\2\0\6\11\11\0\7\11\1\0\7\11\221\0\43\11\35\0\u2ba4\11"+
    "\14\0\27\11\4\0\61\11\u2104\0\u016e\11\2\0\152\11\46\0\7\11"+
    "\14\0\5\11\5\0\1\11\1\0\12\11\1\0\15\11\1\0\5\11"+
    "\1\0\1\11\1\0\2\11\1\0\2\11\1\0\154\11\41\0\u016b\11"+
    "\22\0\100\11\2\0\66\11\50\0\15\11\66\0\2\11\30\0\3\11"+
    "\31\0\1\11\6\0\5\11\1\0\207\11\7\0\1\11\34\0\32\11"+
    "\4\0\1\11\1\0\32\11\13\0\131\11\3\0\6\11\2\0\6\11"+
    "\2\0\6\11\2\0\3\11\3\0\2\11\3\0\2\11\31\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\2\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\2\0\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\1\62\1\63\1\64\1\65\1\0"+
    "\1\66\1\67\1\70\1\71\1\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[64];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\36\0\74\0\36\0\132\0\170\0\226\0\264"+
    "\0\322\0\360\0\36\0\36\0\36\0\36\0\36\0\u010e"+
    "\0\u012c\0\u014a\0\u0168\0\u0186\0\u01a4\0\u01c2\0\u01e0\0\u01fe"+
    "\0\36\0\u021c\0\u023a\0\u0258\0\u0276\0\36\0\226\0\u0294"+
    "\0\36\0\36\0\36\0\36\0\36\0\36\0\36\0\36"+
    "\0\36\0\36\0\36\0\36\0\u02b2\0\u02d0\0\u02ee\0\u030c"+
    "\0\36\0\36\0\36\0\36\0\36\0\36\0\36\0\36"+
    "\0\36\0\u032a\0\u032a\0\36\0\36\0\36\0\36\0\36";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[64];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\11\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\40\0\1\4"+
    "\36\0\1\5\32\0\1\6\2\0\33\6\5\0\2\37"+
    "\1\40\33\0\2\10\1\40\35\0\1\11\1\0\2\11"+
    "\33\0\1\41\7\0\1\42\34\0\1\43\1\44\35\0"+
    "\1\45\35\0\1\46\1\47\34\0\1\50\35\0\1\51"+
    "\35\0\1\52\25\0\1\53\6\0\1\54\1\0\1\55"+
    "\1\56\1\57\1\60\3\0\1\61\25\0\1\62\5\0"+
    "\1\63\27\0\1\64\6\0\1\65\26\0\1\66\35\0"+
    "\1\67\35\0\1\70\35\0\1\71\22\0\2\72\1\0"+
    "\1\73\6\0\1\73\36\0\1\74\1\75\34\0\1\76"+
    "\35\0\1\77\35\0\1\100\22\0\2\72\27\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[840];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\6\1\5\11\11\1\1\11"+
    "\4\1\1\11\2\0\14\11\4\1\11\11\1\1\1\0"+
    "\5\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[64];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  public _OctaveLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _OctaveLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1658) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 12: 
          { yybegin(YYINITIAL); return R_BRACE;
          }
        case 59: break;
        case 49: 
          { yybegin(YYINITIAL); return LESS_THAN_OR_EQUAL;
          }
        case 60: break;
        case 56: 
          { yybegin(YYINITIAL); return ASSIGN_ELEMENT_L_DIV;
          }
        case 61: break;
        case 47: 
          { yybegin(YYINITIAL); return ASSIGN_ELEMENT_AND;
          }
        case 62: break;
        case 31: 
          { yybegin(YYINITIAL); return ASSIGN_PLUS;
          }
        case 63: break;
        case 18: 
          { yybegin(YYINITIAL); return POW_1;
          }
        case 64: break;
        case 57: 
          { yybegin(YYINITIAL); return ASSIGN_ELEMENT_R_DIV;
          }
        case 65: break;
        case 35: 
          { yybegin(YYINITIAL); return ASSIGN_L_DIV;
          }
        case 66: break;
        case 2: 
          { yybegin(YYINITIAL); return CRLF;
          }
        case 67: break;
        case 6: 
          { yybegin(YYINITIAL); return IDENTIFIER;
          }
        case 68: break;
        case 44: 
          { yybegin(YYINITIAL); return TRANSPOSE;
          }
        case 69: break;
        case 54: 
          { yybegin(YYINITIAL); return ASSIGN_ELEMENT_MULTIPLY;
          }
        case 70: break;
        case 21: 
          { yybegin(YYINITIAL); return ELEMENT_AND;
          }
        case 71: break;
        case 36: 
          { yybegin(YYINITIAL); return ASSIGN_R_DIV;
          }
        case 72: break;
        case 15: 
          { yybegin(YYINITIAL); return MULTIPLY;
          }
        case 73: break;
        case 9: 
          { yybegin(YYINITIAL); return L_PAREN;
          }
        case 74: break;
        case 14: 
          { yybegin(YYINITIAL); return ASSIGN;
          }
        case 75: break;
        case 8: 
          { yybegin(YYINITIAL); return COLON;
          }
        case 76: break;
        case 52: 
          { yybegin(YYINITIAL); return NOT_EQUAL_2;
          }
        case 77: break;
        case 43: 
          { yybegin(YYINITIAL); return ELEMENT_POW_1;
          }
        case 78: break;
        case 4: 
          { yybegin(YYINITIAL); return COMMENT;
          }
        case 79: break;
        case 16: 
          { yybegin(YYINITIAL); return L_DIV;
          }
        case 80: break;
        case 19: 
          { yybegin(YYINITIAL); return DOT;
          }
        case 81: break;
        case 29: 
          { yybegin(YYINITIAL); return ASSIGN_MINUS;
          }
        case 82: break;
        case 48: 
          { yybegin(YYINITIAL); return AND;
          }
        case 83: break;
        case 17: 
          { yybegin(YYINITIAL); return R_DIV;
          }
        case 84: break;
        case 40: 
          { yybegin(YYINITIAL); return ELEMENT_MULTIPLY;
          }
        case 85: break;
        case 5: 
          { yybegin(YYINITIAL); return INT;
          }
        case 86: break;
        case 30: 
          { yybegin(YYINITIAL); return INCREMENT;
          }
        case 87: break;
        case 26: 
          { yybegin(YYINITIAL); return NOT_2;
          }
        case 88: break;
        case 41: 
          { yybegin(YYINITIAL); return ELEMENT_L_DIV;
          }
        case 89: break;
        case 11: 
          { yybegin(YYINITIAL); return L_BRACE;
          }
        case 90: break;
        case 53: 
          { yybegin(YYINITIAL); return FLOAT;
          }
        case 91: break;
        case 20: 
          { yybegin(YYINITIAL); return ELEMENT_OR;
          }
        case 92: break;
        case 7: 
          { yybegin(YYINITIAL); return MINUS;
          }
        case 93: break;
        case 3: 
          { yybegin(YYINITIAL); return TokenType.WHITE_SPACE;
          }
        case 94: break;
        case 51: 
          { yybegin(YYINITIAL); return NOT_EQUAL_1;
          }
        case 95: break;
        case 42: 
          { yybegin(YYINITIAL); return ELEMENT_R_DIV;
          }
        case 96: break;
        case 28: 
          { yybegin(YYINITIAL); return DECREMENT;
          }
        case 97: break;
        case 1: 
          { return TokenType.BAD_CHARACTER;
          }
        case 98: break;
        case 27: 
          { yybegin(YYINITIAL); return SEMICOLON;
          }
        case 99: break;
        case 45: 
          { yybegin(YYINITIAL); return ASSIGN_ELEMENT_OR;
          }
        case 100: break;
        case 22: 
          { yybegin(YYINITIAL); return CC_TRANSPOSE;
          }
        case 101: break;
        case 33: 
          { yybegin(YYINITIAL); return ASSIGN_MULTIPLY;
          }
        case 102: break;
        case 10: 
          { yybegin(YYINITIAL); return R_PAREN;
          }
        case 103: break;
        case 32: 
          { yybegin(YYINITIAL); return EQUAL;
          }
        case 104: break;
        case 23: 
          { yybegin(YYINITIAL); return LESS_THAN;
          }
        case 105: break;
        case 38: 
          { yybegin(YYINITIAL); return ELEMENT_MINUS;
          }
        case 106: break;
        case 34: 
          { yybegin(YYINITIAL); return POW_2;
          }
        case 107: break;
        case 58: 
          { yybegin(YYINITIAL); return ASSIGN_ELEMENT_POW_1;
          }
        case 108: break;
        case 39: 
          { yybegin(YYINITIAL); return ELEMENT_PLUS;
          }
        case 109: break;
        case 24: 
          { yybegin(YYINITIAL); return GREATER_THAN;
          }
        case 110: break;
        case 13: 
          { yybegin(YYINITIAL); return PLUS;
          }
        case 111: break;
        case 25: 
          { yybegin(YYINITIAL); return NOT_1;
          }
        case 112: break;
        case 50: 
          { yybegin(YYINITIAL); return GREATER_THAN_OR_EQUAL;
          }
        case 113: break;
        case 46: 
          { yybegin(YYINITIAL); return OR;
          }
        case 114: break;
        case 37: 
          { yybegin(YYINITIAL); return ASSIGN_POW_1;
          }
        case 115: break;
        case 55: 
          { yybegin(YYINITIAL); return ELEMENT_POW_2;
          }
        case 116: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
